"""Tests for MemPalaceProvider — reads from a real mempalace installation."""

import pytest
from pathlib import Path

from extended_thinking.providers.protocol import MemoryChunk, MemoryProvider


# Skip all tests if mempalace isn't installed
MEMPALACE_DIR = Path.home() / ".mempalace"
pytestmark = pytest.mark.skipif(
    not (MEMPALACE_DIR / "palace").exists(),
    reason="mempalace not installed"
)


@pytest.fixture
def provider():
    from extended_thinking.providers.mempalace import MemPalaceProvider
    return MemPalaceProvider()


class TestMemPalaceProvider:

    def test_is_memory_provider(self, provider):
        assert isinstance(provider, MemoryProvider)
        assert provider.name == "mempalace"

    def test_get_stats(self, provider):
        stats = provider.get_stats()
        assert stats["total_memories"] > 0
        assert stats["provider"] == "mempalace"
        assert "total_wings" in stats

    def test_get_recent(self, provider):
        chunks = provider.get_recent(limit=10)
        assert len(chunks) > 0
        assert len(chunks) <= 10
        assert all(isinstance(c, MemoryChunk) for c in chunks)

    def test_chunks_have_provenance(self, provider):
        chunks = provider.get_recent(limit=5)
        for chunk in chunks:
            assert chunk.id
            assert chunk.content
            assert chunk.source
            assert chunk.timestamp

    def test_chunks_have_metadata(self, provider):
        chunks = provider.get_recent(limit=5)
        for chunk in chunks:
            # MemPalace drawers should have wing/room metadata
            assert "wing" in chunk.metadata or len(chunk.metadata) > 0

    def test_search(self, provider):
        results = provider.search("auth", limit=5)
        # Should find something in 60k drawers
        assert len(results) >= 0  # May not match, but shouldn't crash

    def test_search_returns_chunks(self, provider):
        results = provider.search("project", limit=3)
        for r in results:
            assert isinstance(r, MemoryChunk)
            assert r.content

    def test_get_entities(self, provider):
        entities = provider.get_entities()
        # MemPalace KG should have entities
        assert isinstance(entities, list)

    def test_store_and_retrieve_insight(self, provider):
        insight_id = provider.store_insight(
            title="Test Insight from Extended-Thinking",
            description="This is a test insight generated by the DIKW pipeline.",
            related_concepts=["testing", "integration"],
        )
        assert insight_id

        insights = provider.get_insights()
        assert any("Test Insight" in i.content for i in insights)

    def test_auto_provider_includes_mempalace(self):
        """AutoProvider should include mempalace when installed."""
        from extended_thinking.providers.auto import AutoProvider
        auto = AutoProvider()
        stats = auto.get_stats()
        assert "mempalace" in stats["detected_provider"]
