"""Kuzu DDL generated from schema/extended_thinking.yaml (ADR 013).

DO NOT EDIT. Regenerate with:
    python scripts/gen_kuzu.py

Every typed node table inherits a set of system columns (bitemporal timestamps,
namespace, vectors_pending). Every edge table pins FROM/TO to specific node
types per its LinkML slot_usage. Columns whose LinkML name collides with a
Kuzu reserved word are renamed; see COLUMN_MAPPING below for round-tripping
back to the ontology name.
"""

from __future__ import annotations


EXTENDED_THINKING_DDL: list[str] = [
    """CREATE NODE TABLE IF NOT EXISTS Chunk(
    source STRING,
    source_type STRING,
    t_source_created STRING,
    t_ingested STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    desc_text STRING,
    tags STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Concept(
    category STRING,
    frequency INT64,
    first_seen STRING,
    last_seen STRING,
    canonical_id STRING,
    access_count INT64,
    last_accessed STRING,
    source_quote STRING,
    status STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    desc_text STRING,
    tags STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS EnrichmentRun(
    trigger_name STRING,
    source_kind STRING,
    concept_id STRING,
    candidates_returned INT64,
    candidates_accepted INT64,
    gate_trace STRING,
    duration_ms INT64,
    error STRING,
    desc_text STRING,
    tags STRING,
    event_type STRING,
    occurred_at STRING,
    started_at STRING,
    ended_at STRING,
    caused_by STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Fragment(
    content STRING,
    role STRING,
    fragment_type STRING,
    position INT64,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    desc_text STRING,
    tags STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Insight(
    title STRING,
    insight_type STRING,
    confidence DOUBLE,
    detected_at STRING,
    desc_text STRING,
    tags STRING,
    signal_type STRING,
    value DOUBLE,
    algorithm STRING,
    perspective STRING,
    computed_at STRING,
    bearer_id STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS KnowledgeNode(
    source_kind STRING,
    external_id STRING,
    url STRING,
    title STRING,
    abstract STRING,
    theme STRING,
    desc_text STRING,
    tags STRING,
    signal_type STRING,
    value DOUBLE,
    algorithm STRING,
    perspective STRING,
    computed_at STRING,
    bearer_id STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Rationale(
    text STRING,
    cited_node_ids STRING,
    desc_text STRING,
    tags STRING,
    signal_type STRING,
    value DOUBLE,
    algorithm STRING,
    perspective STRING,
    computed_at STRING,
    bearer_id STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Session(
    title STRING,
    source_id STRING,
    message_count INT64,
    metadata STRING,
    desc_text STRING,
    tags STRING,
    event_type STRING,
    occurred_at STRING,
    started_at STRING,
    ended_at STRING,
    caused_by STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Source(
    platform STRING,
    url STRING,
    captured_at STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    desc_text STRING,
    tags STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Suggestion(
    title STRING,
    suggestion_type STRING,
    desc_text STRING,
    tags STRING,
    status STRING,
    signal_type STRING,
    value DOUBLE,
    algorithm STRING,
    perspective STRING,
    computed_at STRING,
    bearer_id STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE NODE TABLE IF NOT EXISTS Wisdom(
    title STRING,
    wisdom_type STRING,
    based_on_sessions INT64,
    based_on_concepts INT64,
    related_concept_ids STRING,
    desc_text STRING,
    tags STRING,
    status STRING,
    signal_type STRING,
    value DOUBLE,
    algorithm STRING,
    perspective STRING,
    computed_at STRING,
    bearer_id STRING,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING,
    vectors_pending BOOL,
    PRIMARY KEY(id)
)""",
    """CREATE REL TABLE IF NOT EXISTS Enriches(
    FROM Concept TO KnowledgeNode,
    relevance DOUBLE,
    trigger STRING,
    gate_verdicts STRING,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
    """CREATE REL TABLE IF NOT EXISTS HasProvenance(
    FROM Concept TO Chunk,
    source_provider STRING,
    llm_model STRING,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
    """CREATE REL TABLE IF NOT EXISTS InformedBy(
    FROM Wisdom TO Concept,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
    """CREATE REL TABLE IF NOT EXISTS ProposalBy(
    FROM Concept TO Concept,
    algorithm STRING,
    parameters_json STRING,
    invoked_at STRING,
    score DOUBLE,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
    """CREATE REL TABLE IF NOT EXISTS RelatesTo(
    FROM Concept TO Concept,
    weight DOUBLE,
    context STRING,
    edge_type STRING,
    access_count INT64,
    last_accessed STRING,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
    """CREATE REL TABLE IF NOT EXISTS Supersedes(
    FROM Concept TO Concept,
    reason STRING,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
    """CREATE REL TABLE IF NOT EXISTS WisdomEnriches(
    FROM Wisdom TO KnowledgeNode,
    relevance DOUBLE,
    trigger STRING,
    gate_verdicts STRING,
    relation_type STRING,
    strength DOUBLE,
    id STRING,
    name STRING,
    created_at STRING,
    updated_at STRING,
    t_valid_from STRING,
    t_valid_to STRING,
    t_created STRING,
    t_expired STRING,
    t_superseded_by STRING,
    namespace STRING,
    et_source STRING
)""",
]


NODE_TABLES: list[str] = ['Chunk', 'Concept', 'EnrichmentRun', 'Fragment', 'Insight', 'KnowledgeNode', 'Rationale', 'Session', 'Source', 'Suggestion', 'Wisdom']


EDGE_TABLES: list[str] = ['Enriches', 'HasProvenance', 'InformedBy', 'ProposalBy', 'RelatesTo', 'Supersedes', 'WisdomEnriches']


# LinkML slot name → Kuzu column name, only listed where renamed.
# Round-trip using this map when reading Kuzu rows back into ontology types.
COLUMN_MAPPING: dict[str, dict[str, str]] = {'Chunk': {'description': 'desc_text'}, 'Concept': {'description': 'desc_text'}, 'EnrichmentRun': {'description': 'desc_text'}, 'Fragment': {'description': 'desc_text'}, 'Insight': {'description': 'desc_text'}, 'KnowledgeNode': {'description': 'desc_text'}, 'Rationale': {'description': 'desc_text'}, 'Session': {'description': 'desc_text'}, 'Source': {'description': 'desc_text'}, 'Suggestion': {'description': 'desc_text'}, 'Wisdom': {'description': 'desc_text'}}
