#!/usr/bin/env python3
"""LinkML → typed Python accessors codegen (ADR 013, Phase 0).

Generates `api/src/extended_thinking/_schema/kuzu_types.py` — a module that
bridges the pydantic domain types (`extended_thinking._schema.models`) with
Kuzu's storage
layer. The pydantic types stay the single source of truth for shape and
validation; this module adds Kuzu-specific serialization.

Outputs from the generated module:

    KUZU_TABLE          : dict[type, str]
        Domain class → Kuzu table name.
    NODE_TYPES          : tuple[type, ...]
        Concrete node classes (Entity/Event/Signal descendants).
    EDGE_TYPES          : tuple[type, ...]
        Concrete edge classes (Relation descendants).
    COLUMN_RENAMES      : dict[type, dict[str, str]]
        LinkML slot → Kuzu column name for each class with any rename.
    SYSTEM_FIELDS_NODE  : tuple[str, ...]
    SYSTEM_FIELDS_EDGE  : tuple[str, ...]
        System-column names the runtime fills in. Consumers ignore.

    to_kuzu_row(obj, *, namespace, source) -> dict
        Serialize a domain instance to a dict of Kuzu column name → value.
        Adds system columns, applies renames, coerces datetime/enum.
    from_kuzu_row(cls, row) -> instance
        Reverse. Drops system columns, undoes renames, reconstructs enums.
    edge_endpoints(obj) -> tuple[src_id, dst_id, props_dict]
        Edge variant: splits source_id / target_id from the property bag.

Design notes:
  - Pydantic models are already generated by `make schema-pydantic`. We
    read the schema ourselves to decide node-vs-edge and column renames,
    so we do not require the generated module at codegen time.
  - Column renames are sourced from the same _KUZU_RENAME_MAP as
    `gen_kuzu.py` (imported) — one source of truth.
  - System fields do NOT appear on the pydantic models; they live only
    on the wire (in to_kuzu_row output / from_kuzu_row input).
  - Edges use `source_id` / `target_id` in pydantic. At write time those
    become the Cypher MATCH clause, not edge properties. `edge_endpoints`
    does that split.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Share the rename map with gen_kuzu.py so the two codegens can't drift.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
from gen_kuzu import (  # noqa: E402
    _KUZU_RENAME_MAP,
    _NODE_SYSTEM_COLUMNS,
    _EDGE_SYSTEM_COLUMNS,
    _ancestors,
    _is_abstract_or_mixin,
    _is_edge_class,
    _is_node_class,
)

from linkml_runtime.utils.schemaview import SchemaView  # noqa: E402


SCHEMA_PATH = REPO_ROOT / "schema" / "extended_thinking.yaml"
OUTPUT_PATH = (
    REPO_ROOT / "api" / "src" / "extended_thinking" / "_schema" / "kuzu_types.py"
)


# ── What each class needs at runtime ──────────────────────────────────

def _collect_class_info(sv: SchemaView) -> dict:
    """For every concrete node/edge class, capture:
        table_name, column_renames, linkml_slot_names.
    """
    nodes: list[str] = []
    edges: list[str] = []
    renames: dict[str, dict[str, str]] = {}
    slots_per_class: dict[str, list[str]] = {}

    for cname in sorted(sv.all_classes(imports=False)):
        if _is_abstract_or_mixin(sv, cname):
            continue
        if _is_node_class(sv, cname):
            nodes.append(cname)
        elif _is_edge_class(sv, cname):
            edges.append(cname)
        else:
            continue

        slot_names = [s.name for s in sv.class_induced_slots(cname)]
        slots_per_class[cname] = slot_names
        rn = {s: _KUZU_RENAME_MAP[s] for s in slot_names if s in _KUZU_RENAME_MAP}
        if rn:
            renames[cname] = rn

    return {
        "nodes": nodes,
        "edges": edges,
        "renames": renames,
        "slots": slots_per_class,
    }


# ── Rendering ─────────────────────────────────────────────────────────

_HEADER = '''"""Typed Kuzu accessors generated from schema/extended_thinking.yaml (ADR 013).

DO NOT EDIT. Regenerate with:
    python scripts/gen_kuzu_types.py

Bridges pydantic domain types (`extended_thinking._schema.models`) with Kuzu's
storage layer. Pydantic stays the single source of truth for shape and
validation; this module adds Kuzu-specific serialization (renames,
system columns, enum coercion).
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, TypeVar

from extended_thinking._schema import models as _m


T = TypeVar("T")


# ── Generated registries ──────────────────────────────────────────────
'''


def _render_registries(info: dict) -> str:
    node_list = ", ".join(f"_m.{n}" for n in info["nodes"])
    edge_list = ", ".join(f"_m.{n}" for n in info["edges"])
    table_entries = [
        *(f"    _m.{n}: {n!r}," for n in info["nodes"]),
        *(f"    _m.{n}: {n!r}," for n in info["edges"]),
    ]
    rename_entries = []
    for cname, rn in sorted(info["renames"].items()):
        pairs = ", ".join(f"{k!r}: {v!r}" for k, v in sorted(rn.items()))
        rename_entries.append(f"    _m.{cname}: {{{pairs}}},")

    node_sys = tuple(_NODE_SYSTEM_COLUMNS.keys())
    edge_sys = tuple(_EDGE_SYSTEM_COLUMNS.keys())

    return f'''
NODE_TYPES: tuple[type, ...] = ({node_list},)


EDGE_TYPES: tuple[type, ...] = ({edge_list},)


KUZU_TABLE: dict[type, str] = {{
{chr(10).join(table_entries)}
}}


# LinkML slot name → Kuzu column name. Present only for classes that have
# at least one renamed slot (e.g., Kuzu's reserved `description`).
COLUMN_RENAMES: dict[type, dict[str, str]] = {{
{chr(10).join(rename_entries) if rename_entries else ""}
}}


SYSTEM_FIELDS_NODE: tuple[str, ...] = {node_sys!r}
SYSTEM_FIELDS_EDGE: tuple[str, ...] = {edge_sys!r}
'''


_HELPERS = '''

# ── Serialization helpers ─────────────────────────────────────────────

def _scalarize(v: Any) -> Any:
    """Coerce Python values Pydantic hands us into Kuzu-friendly scalars.

    - datetime/date → ISO-8601 string (Kuzu columns for these are STRING)
    - Enum          → its string value
    - list          → JSON-encoded string (Kuzu has no array column type
                      for arbitrary Python objects; the schema-level list
                      slots get serialized here)
    """
    import json as _json
    if v is None:
        return v
    if isinstance(v, Enum):
        return v.value
    if isinstance(v, datetime):
        # Preserve tz info when present
        return v.isoformat()
    if hasattr(v, "isoformat") and callable(v.isoformat):
        return v.isoformat()
    if isinstance(v, list):
        return _json.dumps([_scalarize(x) for x in v])
    return v


def _unscalarize(value: Any, target_type: Any) -> Any:
    """Best-effort reverse of `_scalarize` when reading from Kuzu."""
    if value is None or value == "":
        return None
    # Enum coercion: if the pydantic field is an Enum subclass, restore it.
    # Unknown enum values fall through to the raw string — no silent swallow,
    # the return is the semantic outcome of a failed enum round-trip.
    try:
        if isinstance(target_type, type) and issubclass(target_type, Enum):
            return target_type(value)
    except (ValueError, TypeError):
        return value
    return value


def to_kuzu_row(
    obj,
    *,
    namespace: str = "default",
    source: str = "",
) -> dict[str, Any]:
    """Serialize a typed domain instance to a dict ready for Kuzu insert.

    Adds ET system columns (bitemporal timestamps, namespace, source,
    vectors_pending for nodes). Applies column renames. Coerces Python
    types to Kuzu-storable scalars.
    """
    cls = type(obj)
    if cls not in KUZU_TABLE:
        raise ValueError(
            f"{cls.__name__} is not a registered typed-node or typed-edge class; "
            f"only classes under schema/extended_thinking.yaml participate."
        )

    # pydantic v2 — .model_dump() emits a dict with field names.
    raw = obj.model_dump(exclude_none=False)

    out: dict[str, Any] = {}
    renames = COLUMN_RENAMES.get(cls, {})
    for k, v in raw.items():
        kuzu_k = renames.get(k, k)
        out[kuzu_k] = _scalarize(v)

    now = datetime.now(timezone.utc).isoformat()
    system_defaults = {
        "t_valid_from": now,
        "t_valid_to": "",
        "t_created": now,
        "t_expired": "",
        "t_superseded_by": "",
        "namespace": namespace,
        "et_source": source,
    }
    if cls in NODE_TYPES:
        system_defaults["vectors_pending"] = True

    # Don't overwrite a user-provided value for system fields.
    for k, v in system_defaults.items():
        out.setdefault(k, v)

    return out


def from_kuzu_row(cls: type[T], row: dict) -> T:
    """Parse a Kuzu query result row back into a domain instance.

    Drops system columns, reverses renames, reconstructs enums. The caller
    must pass the correct `cls` — Kuzu doesn't label rows with their
    pydantic type.
    """
    if cls not in KUZU_TABLE:
        raise ValueError(f"{cls.__name__} is not a registered typed class")
    renames = COLUMN_RENAMES.get(cls, {})
    reverse = {v: k for k, v in renames.items()}

    d = dict(row)
    # Drop Kuzu internal labels
    d.pop("_id", None)
    d.pop("_label", None)
    # Drop system columns
    for sys in SYSTEM_FIELDS_NODE + SYSTEM_FIELDS_EDGE:
        d.pop(sys, None)
    # Reverse renames
    for kuzu_k, ll_k in reverse.items():
        if kuzu_k in d:
            d[ll_k] = d.pop(kuzu_k)

    # Pydantic handles the remainder: enums, datetime parsing, required checks.
    return cls.model_validate(d)


def edge_endpoints(obj) -> tuple[str, str, dict[str, Any]]:
    """For edge instances: return (source_id, target_id, property_dict).

    The property dict is suitable for a Cypher CREATE ... {props} clause;
    `source_id` and `target_id` are used in the MATCH clause instead.
    """
    cls = type(obj)
    if cls not in EDGE_TYPES:
        raise ValueError(f"{cls.__name__} is not a registered edge type")
    props = to_kuzu_row(obj)
    src = props.pop("source_id")
    tgt = props.pop("target_id")
    return src, tgt, props
'''


def _render_module(info: dict) -> str:
    return _HEADER + _render_registries(info) + _HELPERS


def main() -> int:
    sv = SchemaView(str(SCHEMA_PATH))
    info = _collect_class_info(sv)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_render_module(info), encoding="utf-8")
    print(
        f"wrote {OUTPUT_PATH}  "
        f"({len(info['nodes'])} node types, {len(info['edges'])} edge types, "
        f"{len(info['renames'])} with renames)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
